### ISSUE TITLE
Feature request: pseudo instruction for `lw $register, variable($register)`

### ISSUE THREAD

**Issue by milomg** [1whatleytay/titan#3]
Would it be possible to extend the parser to turn this
```
lw $t3, list($t1)
```
into

```
  la $at, list
  add $at, $at, $t1
  lw $t3, 0($at)
```

I began looking at this but it looks like the parser looks for all symbols followed by parentheses to expand into macros. Would it make sense to only expand macros if they appear at the start of a line (and not have a separate preprocess step)?

**Comment by 1whatleytay** [comment]
Closing with #4
